// <auto-generated />
using System;
using LoanProject.Infrastructure.ReadModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanProject.Infrastructure.ReadModel.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    partial class ReadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanProject.Infrastructure.ReadModel.InstallmentReadModel", b =>
                {
                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InstallmentNo")
                        .HasColumnType("int");

                    b.Property<decimal>("DueAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("LoanId", "InstallmentNo");

                    b.HasIndex("DueDateUtc")
                        .HasDatabaseName("IX_installment_read_model_DueDateUtc");

                    b.HasIndex("PaidAtUtc")
                        .HasDatabaseName("IX_installment_read_model_PaidAtUtc");

                    b.ToTable("installment_read_model", (string)null);
                });

            modelBuilder.Entity("LoanProject.Infrastructure.ReadModel.LoanReadModel", b =>
                {
                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DefaultedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DisbursedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstallmentsPaid")
                        .HasColumnType("int");

                    b.Property<int>("LastProjectedVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextDueDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NextInstallmentNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("OriginatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OutstandingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Principal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SettledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("LoanId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_loan_read_model_Status");

                    b.ToTable("loan_read_model", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
